---
- name: Provisioning servers
  hosts: all
  tasks:
    - name: Install NTP agents on centos
      ansible.builtin.yum:
        name: chrony
        state: present
      when: ansible_distribution == "CentOS"

    - name: Isntall NTP on Ubuntu
      ansible.builtin.apt:
        name: ntp
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Start Service on Centos
      ansible.builtin.service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: Start Service on Ubuntu
      ansible.builtin.service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"
