---
- name: memcache setup
  hosts: web_memcache
  become: yes

  tasks:
    - name: Update OS with latest patches "apt update and apt upgrade"
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes

    - name: Install memcached service
      ansible.builtin.apt:
        name: memcached
        state: present

    - name: Start and Enable memcached service
      ansible.builtin.service:
        name: memcached
        state: started
        enabled: yes

    - name: Chnage memecache config file
      ansible.builtin.copy:
        src: ./template/memcache.j2
        dest: /etc/memcached.conf
      notify:
        - Restart memcached service

  handlers:
    - name: Restart memcached service
      ansible.builtin.service:
        name: memcached
        state: restarted 
