---
# handlers file for post-install
- name: restart service on CentOS
  ansible.builtin.service:
    name: chronyd
    state: restarted
    enabled: yes
  when: ansible_distribution == "Fedora"

- name: restart service on Ubuntu
  ansible.builtin.service:
    name: ntp
    state: restarted
    enabled: yes
  when: ansible_distribution == "Ubuntu
